package:
  name: cactus
  version: "2.7.1"

source:
  url: https://github.com/ComparativeGenomicsToolkit/cactus/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 824f2033bf85f258ca4db3388cd19ecf262c81b23d931e474faad83ad189553a

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config  
  host:
    - python
    - zlib
    - bzip2
    - hdf5
    - lzo
    - tokyocabinet
    - xz
    - libxml2
    - openssl
    - libpng
    - libuuid
    - libcurl
    - libffi
    - libdeflate
    - jemalloc
    - pip
    - abpoa
    - sonlib
    # - matchingandordering
    # - cpecan
    # - pinchesandcacti
  run:
    - python
    - networkx
    - toil
    - sonlib
    # - hal
    # - paffy
    - lastz

test:
  commands:
    - cactus -h
    - hal2assemblyHub.py -h

about:
  home: https://github.com/ComparativeGenomicsToolkit/cactus
  license: MIT
  license_file: LICENSE.txt
  summary: 'A reference-free whole-genome alignment program, as well as a pagenome graph construction toolkit'
